# Generated by Django 4.0.3 on 2022-09-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_numero_telefonico_paciente_numeros'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero_telefonico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
